"""added Deductions model

Revision ID: 26e40931454f
Revises: 
Create Date: 2025-11-19 10:06:37.032032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26e40931454f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.drop_column('misc_deductions')
        batch_op.drop_column('cash_deposits')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('password_hash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('password_hash'), ['password_hash'], unique=True)

    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_deposits', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('misc_deductions', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))

    op.drop_table('deductions')
    # ### end Alembic commands ###
