"""changed name of service column to labor

Revision ID: b38630e2d621
Revises: cdd43cc87b56
Create Date: 2026-01-01 10:52:41.566365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b38630e2d621'
down_revision = 'cdd43cc87b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labor', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.drop_column('labor')

    # ### end Alembic commands ###
